apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: broker-proxy
spec:
  url: <CHANGE_ME>
  insecureSkipTLSVerify: true
  authInfo:
    basic:
      secretRef:
        namespace: default
        name: broker-proxy-secret
