---
apiVersion: v1
kind: Secret
metadata:
  name: ibm-broker-secret
data:
  username: <CHANGE_ME>  # echo -n 'admin' | base64
  password: <CHANGE_ME>

---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: ibm-broker
spec:
  url: <CHANGE_ME>
  insecureSkipTLSVerify: true
  authInfo:
    basic:
      secretRef:
        namespace: default
        name: ibm-broker-secret
